import 'package:flutter/material.dart';
import 'package:flutter_svg/flutter_svg.dart';

class GetLogo extends StatelessWidget {
  final String name;

  const GetLogo({super.key, required this.name});

  @override
  Widget build(BuildContext context) {
    Map<String, String> assetsMap = {
      'Meat': 'assets/chicken-leg.svg',
      'Vegetables': 'assets/lettuce.svg',
      'Fruits': 'assets/orange.svg',
      'Dairy': 'assets/milk.svg',
      'Drinks': 'assets/bubble-tea.svg',
      'Bread': 'assets/bread.svg',
      'Other': 'assets/groceries.svg',
      'Avocado': 'assets/avocado.svg',
      'Summary': 'assets/chicken-leg.svg',
      'White bread (10g)': 'assets/bread 2.svg',
      'Whole grain bread (10g)': 'assets/bread 3.svg',
      'Wheat bread (10g)': 'assets/bread 4.svg',
      'Eye bread (10g)': 'assets/croissant.svg',
      'Rolls (pcs)': 'assets/bread-roll.svg',
      'Brench bread (10g)': 'assets/baguette.svg',
      'Hot dog bread (10g)': 'assets/hotdog.svg',
      'Pretzel (10g)': 'assets/pretzel.svg',
      'Tortilla (10g)': 'assets/tortilla.svg',
      'Cheese (10g)': 'assets/cheese.svg',
      'Yoghurt (10g)': 'assets/yoghurt.svg',
      'Milk (50ml)': 'assets/milk.svg',
      'Milk desserts (10g)': 'assets/sweet-mustard.svg',
      'Cream (50ml)': 'assets/milkshake.svg',
      'Butter (10g)': 'assets/butter.svg',
      'Water (50ml)': 'assets/water.svg',
      'Juice (50ml)': 'assets/juice.svg',
      'Alcohol (50ml)': 'assets/cocktail.svg',
      'Coffee (50ml)': 'assets/ice-coffee.svg',
      'Tea (50ml)': 'assets/tea-bag.svg',
      'Orange (pcs)': 'assets/orange.svg',
      'Lemon (pcs)': 'assets/lemon.svg',
      'Peach (pcs)': 'assets/peach.svg',
      'Watermelon (10g)': 'assets/watermelon.svg',
      'Avocado (pcs)': 'assets/avocado.svg',
      'Chicken (10g)': 'assets/hen.svg',
      'Beef (10g)': 'assets/cattle.svg',
      'Pork (10g)': 'assets/pig.svg',
      'Lamb (10g)': 'assets/sheep.svg',
      'Fish (10g)': 'assets/shark.svg',
      'Sausage (10g)': 'assets/hotdog.svg',
      'Prawns (10g)': 'assets/prawn.svg',
      'Egg (pcs)': 'assets/egg.svg',
      'Ketchup or mustard (10g)': 'assets/mustard.svg',
      'Cookies (10g)': 'assets/cookie.svg',
      'Candy (10g)': 'assets/candy.svg',
      'Honey (10g)': 'assets/honey.svg',
      'Fries (10g)': 'assets/fries.svg',
      'Chips (10g)': 'assets/chips.svg',
      'Mushrooms (10g)': 'assets/mushroom.svg',
      'Carrots (pcs)': 'assets/carrot.svg',
      'Potatoes (10g)': 'assets/potato.svg',
      'Tomatoes (pcs)': 'assets/tomato.svg',
      'Onion (pcs)': 'assets/onion.svg',
      'Paprika (pcs)': 'assets/paprika.svg',
      'Cabbage (pcs)': 'assets/cabbage.svg',
      'Lettuce (10g)': 'assets/lettuce.svg',
      'Cucumber (pcs)': 'assets/cucumber.svg',
      'Brocolli (10g)': 'assets/broccoli.svg',
      'Parsley (pcs)': 'assets/paprika.svg',
      'Garlic (pcs)': 'assets/garlic.svg',
      'Green': 'assets/recycle-bin-green.svg',
      'Yellow': 'assets/recycle-bin-yellow.svg',
      'Red': 'assets/recycle-bin-red.svg',
      'Lettuce': 'assets/lettuce.svg',
      'Money': 'assets/money.svg',
      'Banana (pcs)': 'assets/banana.svg',
      'Berries (10g)': 'assets/berries.svg',
      'Cherries (10g)': 'assets/cherries.svg',
      'Grapes (10g)': 'assets/grapes.svg',
      'Kiwi (pcs)': 'assets/kiwi.svg',
      'Lychee (pcs)': 'assets/lychee.svg',
      'Mango (pcs)': 'assets/mango.svg',
      'Papaya (pcs)': 'assets/papaya.svg',
      'Pear (pcs)': 'assets/pear.svg',
      'Pineapple (pcs)': 'assets/pineapple.svg',
      'Plum (10g)': 'assets/plum.svg',
      'Pomegranate (pcs)': 'assets/pomegranate.svg',
      'Raspberry (10g)': 'assets/raspberry.svg',
      'Strawberry (10g)': 'assets/strawberry.svg',
      'Tangerine (10g)': 'assets/tangerine.svg',
      'Apple (10g)': 'assets/apple.svg',
      'apple': 'assets/apple.svg',
      'bank': 'assets/bank.svg',
      'bread': 'assets/bread 5.svg',
      'cart': 'assets/cart.svg',
      'check_list': 'assets/check-list.svg',
      'date': 'assets/date.svg',
      'fridge': 'assets/fridge.svg',
      'hot_water': 'assets/hot-water.svg',
      'jam': 'assets/jam.svg',
      'leftover': 'assets/leftover.svg',
      'paper_meat': 'assets/paper_meat.svg',
      'zero_bin': 'assets/recycling_bin_zero.svg',
      'remedy': 'assets/remedy.svg',
      'shopping_list': 'assets/shopping_list.svg',
      'husky': 'assets/siberian_husky.svg',
      'small_bin': 'assets/small_green_bin.svg',
      'herbs': 'assets/herbs.svg',
    };
    
    final String assetName = assetsMap[name]!;
    final Widget svg = SvgPicture.asset(
      assetName,
    );
    return svg;
  }
}
